/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.seava.throwable.thrift.rpc;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum BackCode implements org.apache.thrift.TEnum {
  SUCCESS(1),
  PARAME_RROR(2),
  SERVERE_RROR(3),
  NOT_FIND(4),
  NOT_DEFINED(5),
  CLOSED(6),
  OTHER(7);

  private final int value;

  private BackCode(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static BackCode findByValue(int value) { 
    switch (value) {
      case 1:
        return SUCCESS;
      case 2:
        return PARAME_RROR;
      case 3:
        return SERVERE_RROR;
      case 4:
        return NOT_FIND;
      case 5:
        return NOT_DEFINED;
      case 6:
        return CLOSED;
      case 7:
        return OTHER;
      default:
        return null;
    }
  }
}
